spring:
  application:
    name: spring-cloud-eureka
  freemarker:
    prefer-file-system-access: false
server:
  port: 8001

eureka:
  client:
    # 声明是否将自己的信息注册到 Eureka 服务器上
#    register-with-eureka: false
    # 是否到 Eureka 服务器中抓取注册信息
#    fetch-registry: false
    service-url:
      defaultZone: http://peer1:8000/eureka/
  instance:
    hostname: peer2